"""empty message

Revision ID: 9afddbd15070
Revises: c7388ad7866b
Create Date: 2021-12-12 22:14:23.964103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afddbd15070'
down_revision = 'c7388ad7866b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('media', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'media')
    # ### end Alembic commands ###
