"""empty message

Revision ID: a2ad3a9bf0f0
Revises: 5cc9f618914b
Create Date: 2021-12-12 17:28:44.484924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ad3a9bf0f0'
down_revision = '5cc9f618914b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('caption', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'caption')
    # ### end Alembic commands ###
