"""empty message

Revision ID: c7388ad7866b
Revises: 5cc9f618914b
Create Date: 2021-12-12 01:02:12.591257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7388ad7866b'
down_revision = '5cc9f618914b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music', sa.Boolean(), nullable=True),
    sa.Column('tech', sa.Boolean(), nullable=True),
    sa.Column('sports', sa.Boolean(), nullable=True),
    sa.Column('local_news', sa.Boolean(), nullable=True),
    sa.Column('international_news', sa.Boolean(), nullable=True),
    sa.Column('politics', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interests')
    # ### end Alembic commands ###
